### ISSUE TITLE
Invalid VNG file produced for large input

### ISSUE THREAD

**Issue by jamii** [brimdata/super#4840]
```
> zq -f vng -o wrccdc_test.vng 'yield this' wrccdc.zng
> zq -f zson 'count()' wrccdc_test.vng
panic: bad uvarint: -11

goroutine 14 [running]:
github.com/brimdata/zed/zcode.(*Iter).Next(0x2545f40?)
	/home/jamie/zed/zcode/iter.go:26 +0x219
github.com/brimdata/zed/vng/vector.(*PrimitiveReader).ReadBytes(0x0?)
	/home/jamie/zed/vng/vector/primitive.go:210 +0x4c
github.com/brimdata/zed/vng/vector.(*PrimitiveReader).Read(0x1?, 0xc000798f70)
	/home/jamie/zed/vng/vector/primitive.go:194 +0x33
github.com/brimdata/zed/vng/vector.(*FieldReader).Read(...)
	/home/jamie/zed/vng/vector/field.go:44
github.com/brimdata/zed/vng/vector.RecordReader.Read({0xc000a64040, 0x4, 0xc001b6c027?}, 0xc000798f70)
	/home/jamie/zed/vng/vector/record.go:80 +0x147
github.com/brimdata/zed/vng/vector.(*FieldReader).Read(...)
	/home/jamie/zed/vng/vector/field.go:44
github.com/brimdata/zed/vng/vector.RecordReader.Read({0xc00154be00, 0x13, 0x12ec5bf?}, 0xc000798f70)
	/home/jamie/zed/vng/vector/record.go:80 +0x147
github.com/brimdata/zed/vng.(*Reader).Read(0xc000798f50)
	/home/jamie/zed/vng/reader.go:53 +0x147
github.com/brimdata/zed/zbuf.(*scanner).Read(0xc0007a45a0)
	/home/jamie/zed/zbuf/scanner.go:126 +0x51
github.com/brimdata/zed/zbuf.(*puller).Pull(0xc00078bcf0, 0xa0)
	/home/jamie/zed/zbuf/batch.go:85 +0x55
github.com/brimdata/zed/zbuf.(*namedScanner).Pull(0xc0007505c0, 0x50?)
	/home/jamie/zed/zbuf/scanner.go:167 +0x2d
github.com/brimdata/zed/runtime/op/groupby.(*Op).run(0xc0005b42d0)
	/home/jamie/zed/runtime/op/groupby/groupby.go:195 +0xbe
created by github.com/brimdata/zed/runtime/op/groupby.(*Op).Pull.func1
	/home/jamie/zed/runtime/op/groupby/groupby.go:163 +0x6d
```

**Comment by philrz** [comment]
Verified in super commit 4084e01.

After confirming I could still repro the original problem using a `zq` version from around the time the issue was opened, I also find that the equivalent repro steps with SuperDB-era equivalents no longer produces a panic.

```
$ super -version
Version: v1.18.0-206-g4084e011

$ super -f csup -o wrccdc_test.csup -c 'yield this' wrccdc.zng

$ super -f jsup -c 'count()' wrccdc_test.csup
573070060 (uint64)
```

With issues like this I normally like to do a binary search to confirm exactly when the fix arrived. However, in some of my first attempted runs at other commits I found that our VNG file creation was at times so memory inefficient that the process would get OOM-killed even on an EC2 instance with 128 GB of RAM, so I'll just be content knowing the problem is gone.
