### ISSUE TITLE
"panic: invalid memory address or nil pointer dereference" when quiet() is part of join assignment

### ISSUE THREAD

**Issue by philrz** [brimdata/super#5098]
Repro is with GA Zed tagged `v1.15.0`.

To repro, use attached Test data and [conn.zng.gz](https://github.com/brimdata/zed/files/14876523/conn.zng.gz) and [http.zng.gz](https://github.com/brimdata/zed/files/14876524/http.zng.gz) with the following Zed script `add-geo-to-http.zed`:

```
file http.zng.gz
| inner join (
  file conn.zng.gz
  | head 100
  | _path=="conn"
) on uid=uid geo:=quiet(geo)
```

The panic:

```
$ zq -version
Version: v1.15.0

$ zq -I add-geo-to-http.zed 
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go@1.21/libexec/src/runtime/debug/stack.go:24 +0x5e
github.com/brimdata/zed/runtime/sam/op.(*Catcher).Pull.func1()
	/Users/phil/work/zed/runtime/sam/op/catcher.go:25 +0x3d
panic({0x24052c0?, 0x3652d70?})
	/usr/local/opt/go@1.21/libexec/src/runtime/panic.go:914 +0x21f
github.com/brimdata/zed/runtime/sam/op/join.(*Op).buildType(0xc00057c820, 0xc0005ec180, 0x0)
	/Users/phil/work/zed/runtime/sam/op/join/join.go:226 +0x32
github.com/brimdata/zed/runtime/sam/op/join.(*Op).combinedType(0xc00057c820, 0xc0005ec180, 0x0)
	/Users/phil/work/zed/runtime/sam/op/join/join.go:242 +0x7f
github.com/brimdata/zed/runtime/sam/op/join.(*Op).splice(0xc00057c780?, {{0x28c64b0?, 0xc0005ec180?}, 0xc000e92140?, 0xc00049d740?}, {{0x28c6528?, 0xc00014c540?}, 0x3596538?, 0xc000154780?})
	/Users/phil/work/zed/runtime/sam/op/join/join.go:253 +0x1ab
github.com/brimdata/zed/runtime/sam/op/join.(*Op).Pull(0xc00057c820, 0x5?)
	/Users/phil/work/zed/runtime/sam/op/join/join.go:131 +0x538
github.com/brimdata/zed/runtime/sam/op.(*Single).Pull(0xc00014c5e8, 0x20)
	/Users/phil/work/zed/runtime/sam/op/mux.go:134 +0x2b
github.com/brimdata/zed/runtime/sam/op.(*Catcher).Pull(0x3cbf5b8?, 0x0?)
	/Users/phil/work/zed/runtime/sam/op/catcher.go:28 +0x62
github.com/brimdata/zed/runtime/exec.(*Query).Pull(0x4ab82f58?, 0xd8?)
	/Users/phil/work/zed/runtime/exec/query.go:59 +0x3e
github.com/brimdata/zed/zbuf.CopyPuller({0x4ab82f58, 0xc0005b9548}, {0x28c0220, 0xc00011b920})
	/Users/phil/work/zed/zbuf/batch.go:162 +0x4d
github.com/brimdata/zed/cli/zq.(*Command).Run(0xc0004c2a80, {0xc000040740, 0x0, 0x0})
	/Users/phil/work/zed/cli/zq/command.go:162 +0x79e
github.com/brimdata/zed/pkg/charm.path.run({0xc0006a8300?, 0x1, 0x1}, {0xc000040740?, 0x0, 0x0?})
	/Users/phil/work/zed/pkg/charm/path.go:11 +0x79
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x100874b?, {0xc000040730, 0x2, 0x2})
	/Users/phil/work/zed/pkg/charm/charm.go:63 +0x3f
main.main()
	/Users/phil/work/zed/cmd/zq/main.go:11 +0x5b
```

I originally wrote the Zed without the `quiet()` wrapper and caused the crash once I added it.

**Comment by philrz** [comment]
With the implementation of the new `join` as added in #5962, the concept of "join assignment" is gone so this bug is no longer relevant.

In the new syntax, the `join` shown above would now be written as:

```
from http.zng.gz
| inner join (
  from conn.zng.gz
  | head 100
  | _path=='conn'
) on left.uid=right.uid
| values {...left, geo:quiet(right.geo)}
```

i.e., the left-hand and right-hand records that were successfully joined are made available in the `join` output as separate embedded records, so what was previously accomplished via the "join assignment" would now typically be done by what's shown here where `values` is used to produce a top-level record that contains the desired fields, e.g., in this case a spread of the entire left-hand portion along with the `geo` field from the right side.

And the use of `quiet` in this new approach no longer causes a panic. As of super commit 47b1fb7, we see:

```
$ super -version
Version: 47b1fb7d8

$ super -S -c "
from http.zng.gz
| inner join (
  from conn.zng.gz
  | head 100
  | _path=='conn'
) on left.uid=right.uid
| values {...left, geo:quiet(right.geo)}"

{
    _path: "http",
    ts: 2018-03-23T19:58:23.069622Z,
    uid: "C0cITj1npN1MxudrR1",
    id: {
        orig_h: 10.0.0.111,
        orig_p: 47967 (port=uint16),
        resp_h: 10.47.1.142,
        resp_p: 80 (port)
    },
    trans_depth: 1 (uint64),
    method: "GET",
    host: null (string),
    uri: "/",
    referrer: null (string),
    version: "1.1",
    user_agent: "check_http/v2.0 (monitoring-plugins 2.0)",
    origin: null (string),
    request_body_len: 0 (uint64),
    response_body_len: 17336 (uint64),
    status_code: 200 (uint64),
    status_msg: "OK",
    info_code: null (uint64),
    info_msg: null (string),
    tags: |[]| (|[zenum=string]|),
    username: null (string),
    password: null (string),
    proxied: null (|[string]|),
    orig_fuids: null ([string]),
    orig_filenames: null ([string]),
    orig_mime_types: null ([string]),
    resp_fuids: [
        "FJNiXb4EHiPlXc2G7"
    ],
    resp_filenames: null ([string]),
    resp_mime_types: [
        "text/html"
    ],
    geo: error("quiet")
}
...
```

i.e., the explicit `error("quiet")` is present rather than the `error("missing")` we've have gotten if we just did `values {...left, geo:right.geo}`.
