### ISSUE TITLE
SEGV when querying Parquet for mgbench bench1/q3

### ISSUE THREAD

**Issue by philrz** [brimdata/super#5500]
Repro is with:

* super commit cbb40f5
* Test data from `s3://brim-sampledata/mgbench/bench1-from-duckdb-table.parquet`
* The [bench1/q3 query](https://github.com/brimdata/mgbench-private/blob/main/bench1/q3/q3.spq)

This query used to fail due to prior bug #5463 which has recently been fixed. Now that we're past that, it's seeing a SEGV when I run the query against Parquet. Interestingly, I didn't see the failure when running the same query against CSUP.

```
$ super -version
Version: v1.18.0-167-gcbb40f53

$ SUPER_VAM=1 super -c '
from "bench1-from-duckdb-table.parquet"
| where
    machine_name=="babbage"
    and load_fifteen != null
    and load_five != null
    and load_one != null
    and mem_free != null
    and swap_free != null
    and log_time >= 2017-01-01T00:00:00Z
| summarize
    load_fifteen_avg := avg(load_fifteen),
    load_five_avg := avg (load_five),
    load_one_avg := avg (load_one),
    mem_free_avg := avg (mem_free),
    swap_free_avg := avg (swap_free)
    by hr := bucket(log_time, 1h)
| sort hr
| put _time_parts := split(strftime("%Y-%m-%d,%H", hr), ",")
| put
    dt := _time_parts[0],
    hr := uint8(_time_parts[1])
| drop _time_parts'

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9235689]

goroutine 69 [running]:
github.com/brimdata/super.(*Context).LookupTypeRecord(0x0, {0xc008e47dc0, 0x2, 0x2})
	/Users/phil/work/super/context.go:106 +0x149
github.com/brimdata/super.(*Context).MustLookupTypeRecord(...)
	/Users/phil/work/super/context.go:151
github.com/brimdata/super/runtime/vam/expr/agg.(*avg).ResultAsPartial(0xc0016bad90, 0x0)
	/Users/phil/work/super/runtime/vam/expr/agg/avg.go:61 +0x139
github.com/brimdata/super/runtime/vam/op/summarize.(*superTable).materializeAgg(0xc026a96aa0, 0x0)
	/Users/phil/work/super/runtime/vam/op/summarize/agg.go:119 +0xf1
github.com/brimdata/super/runtime/vam/op/summarize.(*superTable).materialize(0xc026a96aa0)
	/Users/phil/work/super/runtime/vam/op/summarize/agg.go:99 +0x230
github.com/brimdata/super/runtime/vam/op/summarize.(*Summarize).next(0xc019df5e88?)
	/Users/phil/work/super/runtime/vam/op/summarize/summarize.go:130 +0x85
github.com/brimdata/super/runtime/vam/op/summarize.(*Summarize).Pull(0xc001aa9e40, 0x0?)
	/Users/phil/work/super/runtime/vam/op/summarize/summarize.go:66 +0x3a5
github.com/brimdata/super/runtime/vam/op.(*combineParent).run(0xc002172000)
	/Users/phil/work/super/runtime/vam/op/combine.go:110 +0x3f
created by github.com/brimdata/super/runtime/vam/op.(*Combine).Pull.func1 in goroutine 13
	/Users/phil/work/super/runtime/vam/op/combine.go:42 +0x35
```

**Comment by philrz** [comment]
Verified in super commit e7d0376.

The query now runs successfully without triggering SEGV.

```
$ super -version
Version: v1.18.0-170-ge7d03764

$ SUPER_VAM=1 super -c '
from "bench1-from-duckdb-table.parquet"
| where
    machine_name=="babbage"
    and load_fifteen != null
    and load_five != null
    and load_one != null
    and mem_free != null
    and swap_free != null
    and log_time >= 2017-01-01T00:00:00Z
| summarize
    load_fifteen_avg := avg(load_fifteen),
    load_five_avg := avg (load_five),
    load_one_avg := avg (load_one),
    mem_free_avg := avg (mem_free),
    swap_free_avg := avg (swap_free)
    by hr := bucket(log_time, 1h)
| sort hr
| put _time_parts := split(strftime("%Y-%m-%d,%H", hr), ",")
| put
    dt := _time_parts[0],
    hr := uint8(_time_parts[1])
| drop _time_parts'

{hr:0(uint8),load_fifteen_avg:0.12074265427003472,load_five_avg:0.09436412433446464,load_one_avg:0.08892598874241477,mem_free_avg:2.1703590127118644e+06,swap_free_avg:8388604.,dt:"2017-01-01"}
...
{hr:14(uint8),load_fifteen_avg:0.11743057240671087,load_five_avg:0.09292011533942178,load_one_avg:0.09494392676540067,mem_free_avg:2.143345628504673e+06,swap_free_avg:8388604.,dt:"2017-01-11"}
```

Thanks @mattnibs!
